language: ruby
sudo: required
rvm:
  - 2.1
  - 2.2
  - 2.3.0
cache: bundler
install:
  - 'gem install bundler'
  - 'bundle install --jobs=3 --retry=3'
script:
  - 'bundle exec rake'
services:
  - docker
notifications:
  email: false
