language: ruby
sudo: required
rvm:
  - 2.2
  - 2.3.0
env:
  -
  - ACTIVE_RECORD_VERSION=4.0.0
  - ACTIVE_RECORD_VERSION=4.1.0
  - ACTIVE_RECORD_VERSION=4.2.0
  - ACTIVE_RECORD_VERSION=5.0.0
cache: bundler
install:
  - 'gem install bundler'
  - 'bundle install --jobs=3 --retry=3'
script:
  - 'bundle exec rake'
services:
  - docker
notifications:
  email: false
